### ISSUE TITLE
Misleading error for invalid JSON

### ISSUE THREAD

**Issue by workergnome** [DDMAL/tripoli#15]
If you give it a manifest that has invalid JSON, it says 

```
{
  "message": "Could not retrieve manifest at 'https://www.example.com'"
}
```

Even if there's a file there.  Might be worth catching the difference between a missing file and invalid JSON?

(btw, this is great.)

**Comment by lexpar** [comment]
This looks to be an issue with the website, since the validator itself does not fetch manifests over http - I thought it might make sense to allow users to decide how to get the manifests to the validator. 

I'll make this error clearer soon - at this point it's just catching any error in retrieving and parsing the manifest and replying with the error you posted above. 

Thanks for the kind words.

**Comment by workergnome** [comment]
No worries!

**Comment by lexpar** [comment]
There is now a distinction between a network error (timeout or other) and a failure to parse json from the response.

**Comment by workergnome** [comment]
Thanks!
